trigger:
- master
- development

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: pip install -r requirements.txt
  displayName: 'Install required packages'

- script: python test_fairlearn.py
  displayName: 'Run tests'
