parameters:
  platforms: { Linux: ubuntu-latest, WindowsOld: vs2017-win2016, WindowsLatest: windows-latest }
  pyVersions: [3.6, 3.7, 3.8]

jobs:
  - ${{ each plat in parameters.platforms }}:
    - ${{ each pyVer in parameters.pyVersions }}:
      - job:
        displayName: ${{ format('{0} {1}', plat.Key, pyVer) }}
        pool:
          vmImage: ${{ plat.value }}

        steps:
          - task: UsePythonVersion@0
            displayName: 'Use Python ${{pyVer}}'
            inputs:
              versionSpec: '${{pyVer}}' 
              addToPath: true

          - bash: |
              pip install numpy==1.17.2