parameters:
  platforms: { Linux: ubuntu-latest, WindowsOld: vs2017-win2016, WindowsLatest: windows-latest }
  pyVersions: [3.6, 3.7, 3.8]
  pipsetuptools: [ False, True ]
  pipnpsci: [ 'numpy==1.17.2', 'numpy>=1.17.2']

jobs:
  - ${{ each plat in parameters.platforms }}:
    - ${{ each pyVer in parameters.pyVersions }}:
      - ${{ each npsci in parameters.pipnpsci }}:
        - ${{ each sut in parameters.pipsetuptools }}:
          - job:
            displayName: ${{ format('{0} {1} {2} {3}', plat.Key, pyVer, npsci, sut) }}
            pool:
              vmImage: ${{ plat.value }}

            steps:
              - task: UsePythonVersion@0
                displayName: 'Use Python ${{pyVer}}'
                inputs:
                  versionSpec: '${{pyVer}}' 
                  addToPath: true

              - ${{ if eq(sut, 'True') }}:
                - template: python-infra-upgrade-steps-template.yml

              - bash: |
                  pip install ${{npsci}} 
                displayName: Run pip command for ${{npsci}} '${{sut}}'