name: PR-Gate

on:
  push:
    branches:
    - master
    - rolutz/github_actions
  pull_request:
    branches:
    - master
    - release/*
    - rolutz/github_actions

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
        - ubuntu-16.04
        - vs2017-win2016
        - macos-latest
        pythonVersion:
        - 3.6
        - 3.7
        - 3.8

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.pythonVersion }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.pythonVersion }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 .
    - name: Test with pytest
      run: |
        pytest ./test/unit/reductions/exponentiated_gradient
